name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v17

      - name: Build
        run: nix build
